prep-javascript-variables exercise - Heather Merizan
HMerizan/prep-0922-code-solutions pull request #10
Opened 2022-10-01 19:33 UTC by HMerizan

<img width="646" alt="Screen Shot 2022-10-01 at 12 27 58 PM" src="https://user-images.githubusercontent.com/90870500/193425393-3c71e00d-470a-4716-8020-27ccb2038f02.png">

2022-10-02 20:16 UTC, thebearingedge requested changes

2022-10-02 20:16 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    console.log('Value of nothing:', nothing);
For numbers, `null`, and booleans we want to leave off the quotes so that the javascript engine doesn't interpret them as strings.

2022-10-03 08:41 UTC, HMerizan commented
<img width="643" alt="Screen Shot 2022-10-03 at 1 34 58 AM" src="https://user-images.githubusercontent.com/90870500/193535535-e3867b68-d960-4244-b090-cb2ff1d42dfa.png">

2022-10-03 15:12 UTC, thebearingedge approved these changes

2022-10-03 22:10 UTC, merged