prep-javascript-arrays - Heather Merizan
HMerizan/prep-0922-code-solutions pull request #12
Opened 2022-10-04 03:25 UTC by HMerizan

<img width="639" alt="Screen Shot 2022-10-03 at 8 21 42 PM" src="https://user-images.githubusercontent.com/90870500/193727834-730a248c-6f08-4a4e-9118-4f6bd874f56b.png">

2022-10-04 14:25 UTC, thebearingedge requested changes

2022-10-04 14:25 UTC, thebearingedge commented on prep-javascript-arrays/main.js
> +console.log('the last element of the array is', lastElement);
We can calculate the last index of any array by subtracting 1 from its length. The result can be used to get the last element of the array.

```js
var lastElement = languages[length - 1];
```

2022-10-05 00:02 UTC, HMerizan commented
<img width="645" alt="Screen Shot 2022-10-04 at 4 56 40 PM" src="https://user-images.githubusercontent.com/90870500/193951961-1f45aaad-96d2-4c2c-a94d-e2f5dff16f92.png">

2022-10-05 01:16 UTC, thebearingedge approved these changes

2022-10-05 01:17 UTC, merged